export const NETFLIX_RESET_PASSWORD = "NETFLIX_RESET_PASSWORD";
export const SUBSCRIPTION_EXPIRY_NOTIFIER = "SUBSCRIPTION_EXPIRY_NOTIFIER";
export const SUBS_END_DISABLE_ACCOUNT = "SUBS_END_DISABLE_ACCOUNT";
