/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardTransactionIndexRouteImport } from './routes/_dashboard/transaction/index'
import { Route as DashboardProductIndexRouteImport } from './routes/_dashboard/product/index'
import { Route as DashboardPlatformProductIndexRouteImport } from './routes/_dashboard/platform-product/index'
import { Route as DashboardLogsIndexRouteImport } from './routes/_dashboard/logs/index'
import { Route as DashboardExpenseIndexRouteImport } from './routes/_dashboard/expense/index'
import { Route as DashboardEmailIndexRouteImport } from './routes/_dashboard/email/index'
import { Route as DashboardEmailSubjectIndexRouteImport } from './routes/_dashboard/email-subject/index'
import { Route as DashboardEmailMessageIndexRouteImport } from './routes/_dashboard/email-message/index'
import { Route as DashboardBotIndexRouteImport } from './routes/_dashboard/bot/index'
import { Route as DashboardAccountIndexRouteImport } from './routes/_dashboard/account/index'
import { Route as DashboardTransactionCreateRouteImport } from './routes/_dashboard/transaction/create'
import { Route as DashboardProductCreateRouteImport } from './routes/_dashboard/product/create'
import { Route as DashboardPlatformProductCreateRouteImport } from './routes/_dashboard/platform-product/create'
import { Route as DashboardPlatformProductIdRouteImport } from './routes/_dashboard/platform-product/$id'
import { Route as DashboardExpenseCreateRouteImport } from './routes/_dashboard/expense/create'
import { Route as DashboardEmailCreateRouteImport } from './routes/_dashboard/email/create'
import { Route as DashboardEmailIdRouteImport } from './routes/_dashboard/email/$id'
import { Route as DashboardEmailSubjectCreateRouteImport } from './routes/_dashboard/email-subject/create'
import { Route as DashboardEmailSubjectIdRouteImport } from './routes/_dashboard/email-subject/$id'
import { Route as DashboardBotCommandProgressRouteImport } from './routes/_dashboard/bot/command-progress'
import { Route as DashboardBotBotNameRouteImport } from './routes/_dashboard/bot/$botName'
import { Route as DashboardAccountCreateRouteImport } from './routes/_dashboard/account/create'
import { Route as DashboardEmailConnectIdRouteImport } from './routes/_dashboard/email/connect.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionIndexRoute =
  DashboardTransactionIndexRouteImport.update({
    id: '/transaction/',
    path: '/transaction/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductIndexRoute = DashboardProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformProductIndexRoute =
  DashboardPlatformProductIndexRouteImport.update({
    id: '/platform-product/',
    path: '/platform-product/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLogsIndexRoute = DashboardLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpenseIndexRoute = DashboardExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailIndexRoute = DashboardEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailSubjectIndexRoute =
  DashboardEmailSubjectIndexRouteImport.update({
    id: '/email-subject/',
    path: '/email-subject/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmailMessageIndexRoute =
  DashboardEmailMessageIndexRouteImport.update({
    id: '/email-message/',
    path: '/email-message/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBotIndexRoute = DashboardBotIndexRouteImport.update({
  id: '/bot/',
  path: '/bot/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionCreateRoute =
  DashboardTransactionCreateRouteImport.update({
    id: '/transaction/create',
    path: '/transaction/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductCreateRoute = DashboardProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlatformProductCreateRoute =
  DashboardPlatformProductCreateRouteImport.update({
    id: '/platform-product/create',
    path: '/platform-product/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlatformProductIdRoute =
  DashboardPlatformProductIdRouteImport.update({
    id: '/platform-product/$id',
    path: '/platform-product/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardExpenseCreateRoute = DashboardExpenseCreateRouteImport.update({
  id: '/expense/create',
  path: '/expense/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailCreateRoute = DashboardEmailCreateRouteImport.update({
  id: '/email/create',
  path: '/email/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailIdRoute = DashboardEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailSubjectCreateRoute =
  DashboardEmailSubjectCreateRouteImport.update({
    id: '/email-subject/create',
    path: '/email-subject/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmailSubjectIdRoute = DashboardEmailSubjectIdRouteImport.update({
  id: '/email-subject/$id',
  path: '/email-subject/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBotCommandProgressRoute =
  DashboardBotCommandProgressRouteImport.update({
    id: '/bot/command-progress',
    path: '/bot/command-progress',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBotBotNameRoute = DashboardBotBotNameRouteImport.update({
  id: '/bot/$botName',
  path: '/bot/$botName',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountCreateRoute = DashboardAccountCreateRouteImport.update({
  id: '/account/create',
  path: '/account/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailConnectIdRoute = DashboardEmailConnectIdRouteImport.update({
  id: '/email/connect/$id',
  path: '/email/connect/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/account/create': typeof DashboardAccountCreateRoute
  '/bot/$botName': typeof DashboardBotBotNameRoute
  '/bot/command-progress': typeof DashboardBotCommandProgressRoute
  '/email-subject/$id': typeof DashboardEmailSubjectIdRoute
  '/email-subject/create': typeof DashboardEmailSubjectCreateRoute
  '/email/$id': typeof DashboardEmailIdRoute
  '/email/create': typeof DashboardEmailCreateRoute
  '/expense/create': typeof DashboardExpenseCreateRoute
  '/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/product/create': typeof DashboardProductCreateRoute
  '/transaction/create': typeof DashboardTransactionCreateRoute
  '/account/': typeof DashboardAccountIndexRoute
  '/bot/': typeof DashboardBotIndexRoute
  '/email-message/': typeof DashboardEmailMessageIndexRoute
  '/email-subject/': typeof DashboardEmailSubjectIndexRoute
  '/email/': typeof DashboardEmailIndexRoute
  '/expense/': typeof DashboardExpenseIndexRoute
  '/logs/': typeof DashboardLogsIndexRoute
  '/platform-product/': typeof DashboardPlatformProductIndexRoute
  '/product/': typeof DashboardProductIndexRoute
  '/transaction/': typeof DashboardTransactionIndexRoute
  '/email/connect/$id': typeof DashboardEmailConnectIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/account/create': typeof DashboardAccountCreateRoute
  '/bot/$botName': typeof DashboardBotBotNameRoute
  '/bot/command-progress': typeof DashboardBotCommandProgressRoute
  '/email-subject/$id': typeof DashboardEmailSubjectIdRoute
  '/email-subject/create': typeof DashboardEmailSubjectCreateRoute
  '/email/$id': typeof DashboardEmailIdRoute
  '/email/create': typeof DashboardEmailCreateRoute
  '/expense/create': typeof DashboardExpenseCreateRoute
  '/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/product/create': typeof DashboardProductCreateRoute
  '/transaction/create': typeof DashboardTransactionCreateRoute
  '/account': typeof DashboardAccountIndexRoute
  '/bot': typeof DashboardBotIndexRoute
  '/email-message': typeof DashboardEmailMessageIndexRoute
  '/email-subject': typeof DashboardEmailSubjectIndexRoute
  '/email': typeof DashboardEmailIndexRoute
  '/expense': typeof DashboardExpenseIndexRoute
  '/logs': typeof DashboardLogsIndexRoute
  '/platform-product': typeof DashboardPlatformProductIndexRoute
  '/product': typeof DashboardProductIndexRoute
  '/transaction': typeof DashboardTransactionIndexRoute
  '/email/connect/$id': typeof DashboardEmailConnectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/account/create': typeof DashboardAccountCreateRoute
  '/_dashboard/bot/$botName': typeof DashboardBotBotNameRoute
  '/_dashboard/bot/command-progress': typeof DashboardBotCommandProgressRoute
  '/_dashboard/email-subject/$id': typeof DashboardEmailSubjectIdRoute
  '/_dashboard/email-subject/create': typeof DashboardEmailSubjectCreateRoute
  '/_dashboard/email/$id': typeof DashboardEmailIdRoute
  '/_dashboard/email/create': typeof DashboardEmailCreateRoute
  '/_dashboard/expense/create': typeof DashboardExpenseCreateRoute
  '/_dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/_dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/_dashboard/product/create': typeof DashboardProductCreateRoute
  '/_dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/_dashboard/account/': typeof DashboardAccountIndexRoute
  '/_dashboard/bot/': typeof DashboardBotIndexRoute
  '/_dashboard/email-message/': typeof DashboardEmailMessageIndexRoute
  '/_dashboard/email-subject/': typeof DashboardEmailSubjectIndexRoute
  '/_dashboard/email/': typeof DashboardEmailIndexRoute
  '/_dashboard/expense/': typeof DashboardExpenseIndexRoute
  '/_dashboard/logs/': typeof DashboardLogsIndexRoute
  '/_dashboard/platform-product/': typeof DashboardPlatformProductIndexRoute
  '/_dashboard/product/': typeof DashboardProductIndexRoute
  '/_dashboard/transaction/': typeof DashboardTransactionIndexRoute
  '/_dashboard/email/connect/$id': typeof DashboardEmailConnectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account/create'
    | '/bot/$botName'
    | '/bot/command-progress'
    | '/email-subject/$id'
    | '/email-subject/create'
    | '/email/$id'
    | '/email/create'
    | '/expense/create'
    | '/platform-product/$id'
    | '/platform-product/create'
    | '/product/create'
    | '/transaction/create'
    | '/account/'
    | '/bot/'
    | '/email-message/'
    | '/email-subject/'
    | '/email/'
    | '/expense/'
    | '/logs/'
    | '/platform-product/'
    | '/product/'
    | '/transaction/'
    | '/email/connect/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/account/create'
    | '/bot/$botName'
    | '/bot/command-progress'
    | '/email-subject/$id'
    | '/email-subject/create'
    | '/email/$id'
    | '/email/create'
    | '/expense/create'
    | '/platform-product/$id'
    | '/platform-product/create'
    | '/product/create'
    | '/transaction/create'
    | '/account'
    | '/bot'
    | '/email-message'
    | '/email-subject'
    | '/email'
    | '/expense'
    | '/logs'
    | '/platform-product'
    | '/product'
    | '/transaction'
    | '/email/connect/$id'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/account/create'
    | '/_dashboard/bot/$botName'
    | '/_dashboard/bot/command-progress'
    | '/_dashboard/email-subject/$id'
    | '/_dashboard/email-subject/create'
    | '/_dashboard/email/$id'
    | '/_dashboard/email/create'
    | '/_dashboard/expense/create'
    | '/_dashboard/platform-product/$id'
    | '/_dashboard/platform-product/create'
    | '/_dashboard/product/create'
    | '/_dashboard/transaction/create'
    | '/_dashboard/account/'
    | '/_dashboard/bot/'
    | '/_dashboard/email-message/'
    | '/_dashboard/email-subject/'
    | '/_dashboard/email/'
    | '/_dashboard/expense/'
    | '/_dashboard/logs/'
    | '/_dashboard/platform-product/'
    | '/_dashboard/product/'
    | '/_dashboard/transaction/'
    | '/_dashboard/email/connect/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/transaction/': {
      id: '/_dashboard/transaction/'
      path: '/transaction'
      fullPath: '/transaction/'
      preLoaderRoute: typeof DashboardTransactionIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/product/': {
      id: '/_dashboard/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof DashboardProductIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/platform-product/': {
      id: '/_dashboard/platform-product/'
      path: '/platform-product'
      fullPath: '/platform-product/'
      preLoaderRoute: typeof DashboardPlatformProductIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logs/': {
      id: '/_dashboard/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof DashboardLogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/expense/': {
      id: '/_dashboard/expense/'
      path: '/expense'
      fullPath: '/expense/'
      preLoaderRoute: typeof DashboardExpenseIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/': {
      id: '/_dashboard/email/'
      path: '/email'
      fullPath: '/email/'
      preLoaderRoute: typeof DashboardEmailIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email-subject/': {
      id: '/_dashboard/email-subject/'
      path: '/email-subject'
      fullPath: '/email-subject/'
      preLoaderRoute: typeof DashboardEmailSubjectIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email-message/': {
      id: '/_dashboard/email-message/'
      path: '/email-message'
      fullPath: '/email-message/'
      preLoaderRoute: typeof DashboardEmailMessageIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bot/': {
      id: '/_dashboard/bot/'
      path: '/bot'
      fullPath: '/bot/'
      preLoaderRoute: typeof DashboardBotIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/': {
      id: '/_dashboard/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/transaction/create': {
      id: '/_dashboard/transaction/create'
      path: '/transaction/create'
      fullPath: '/transaction/create'
      preLoaderRoute: typeof DashboardTransactionCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/product/create': {
      id: '/_dashboard/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof DashboardProductCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/platform-product/create': {
      id: '/_dashboard/platform-product/create'
      path: '/platform-product/create'
      fullPath: '/platform-product/create'
      preLoaderRoute: typeof DashboardPlatformProductCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/platform-product/$id': {
      id: '/_dashboard/platform-product/$id'
      path: '/platform-product/$id'
      fullPath: '/platform-product/$id'
      preLoaderRoute: typeof DashboardPlatformProductIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/expense/create': {
      id: '/_dashboard/expense/create'
      path: '/expense/create'
      fullPath: '/expense/create'
      preLoaderRoute: typeof DashboardExpenseCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/create': {
      id: '/_dashboard/email/create'
      path: '/email/create'
      fullPath: '/email/create'
      preLoaderRoute: typeof DashboardEmailCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/$id': {
      id: '/_dashboard/email/$id'
      path: '/email/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof DashboardEmailIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email-subject/create': {
      id: '/_dashboard/email-subject/create'
      path: '/email-subject/create'
      fullPath: '/email-subject/create'
      preLoaderRoute: typeof DashboardEmailSubjectCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email-subject/$id': {
      id: '/_dashboard/email-subject/$id'
      path: '/email-subject/$id'
      fullPath: '/email-subject/$id'
      preLoaderRoute: typeof DashboardEmailSubjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bot/command-progress': {
      id: '/_dashboard/bot/command-progress'
      path: '/bot/command-progress'
      fullPath: '/bot/command-progress'
      preLoaderRoute: typeof DashboardBotCommandProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bot/$botName': {
      id: '/_dashboard/bot/$botName'
      path: '/bot/$botName'
      fullPath: '/bot/$botName'
      preLoaderRoute: typeof DashboardBotBotNameRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/create': {
      id: '/_dashboard/account/create'
      path: '/account/create'
      fullPath: '/account/create'
      preLoaderRoute: typeof DashboardAccountCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/connect/$id': {
      id: '/_dashboard/email/connect/$id'
      path: '/email/connect/$id'
      fullPath: '/email/connect/$id'
      preLoaderRoute: typeof DashboardEmailConnectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountCreateRoute: typeof DashboardAccountCreateRoute
  DashboardBotBotNameRoute: typeof DashboardBotBotNameRoute
  DashboardBotCommandProgressRoute: typeof DashboardBotCommandProgressRoute
  DashboardEmailSubjectIdRoute: typeof DashboardEmailSubjectIdRoute
  DashboardEmailSubjectCreateRoute: typeof DashboardEmailSubjectCreateRoute
  DashboardEmailIdRoute: typeof DashboardEmailIdRoute
  DashboardEmailCreateRoute: typeof DashboardEmailCreateRoute
  DashboardExpenseCreateRoute: typeof DashboardExpenseCreateRoute
  DashboardPlatformProductIdRoute: typeof DashboardPlatformProductIdRoute
  DashboardPlatformProductCreateRoute: typeof DashboardPlatformProductCreateRoute
  DashboardProductCreateRoute: typeof DashboardProductCreateRoute
  DashboardTransactionCreateRoute: typeof DashboardTransactionCreateRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardBotIndexRoute: typeof DashboardBotIndexRoute
  DashboardEmailMessageIndexRoute: typeof DashboardEmailMessageIndexRoute
  DashboardEmailSubjectIndexRoute: typeof DashboardEmailSubjectIndexRoute
  DashboardEmailIndexRoute: typeof DashboardEmailIndexRoute
  DashboardExpenseIndexRoute: typeof DashboardExpenseIndexRoute
  DashboardLogsIndexRoute: typeof DashboardLogsIndexRoute
  DashboardPlatformProductIndexRoute: typeof DashboardPlatformProductIndexRoute
  DashboardProductIndexRoute: typeof DashboardProductIndexRoute
  DashboardTransactionIndexRoute: typeof DashboardTransactionIndexRoute
  DashboardEmailConnectIdRoute: typeof DashboardEmailConnectIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountCreateRoute: DashboardAccountCreateRoute,
  DashboardBotBotNameRoute: DashboardBotBotNameRoute,
  DashboardBotCommandProgressRoute: DashboardBotCommandProgressRoute,
  DashboardEmailSubjectIdRoute: DashboardEmailSubjectIdRoute,
  DashboardEmailSubjectCreateRoute: DashboardEmailSubjectCreateRoute,
  DashboardEmailIdRoute: DashboardEmailIdRoute,
  DashboardEmailCreateRoute: DashboardEmailCreateRoute,
  DashboardExpenseCreateRoute: DashboardExpenseCreateRoute,
  DashboardPlatformProductIdRoute: DashboardPlatformProductIdRoute,
  DashboardPlatformProductCreateRoute: DashboardPlatformProductCreateRoute,
  DashboardProductCreateRoute: DashboardProductCreateRoute,
  DashboardTransactionCreateRoute: DashboardTransactionCreateRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardBotIndexRoute: DashboardBotIndexRoute,
  DashboardEmailMessageIndexRoute: DashboardEmailMessageIndexRoute,
  DashboardEmailSubjectIndexRoute: DashboardEmailSubjectIndexRoute,
  DashboardEmailIndexRoute: DashboardEmailIndexRoute,
  DashboardExpenseIndexRoute: DashboardExpenseIndexRoute,
  DashboardLogsIndexRoute: DashboardLogsIndexRoute,
  DashboardPlatformProductIndexRoute: DashboardPlatformProductIndexRoute,
  DashboardProductIndexRoute: DashboardProductIndexRoute,
  DashboardTransactionIndexRoute: DashboardTransactionIndexRoute,
  DashboardEmailConnectIdRoute: DashboardEmailConnectIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
